### ISSUE TITLE
Add functionality to UI

### ISSUE THREAD

**Issue by lilyMonika** [lilyMonika/Team-Source-Control-Project#17]
@Tfair5597 Let's split up adding functionalities to the UI. I'll take on Registering and Updating data as well as the forms for them.

**Comment by Tfair5597** [comment]
So i take up deleting the information?

**Comment by lilyMonika** [comment]
Deleting and Displaying the data on the listbox, yeah.

**Comment by lilyMonika** [comment]
I've also updated the `master` branch so make sure you work on that one.

**Comment by Tfair5597** [comment]
Thanks, as far as I know at the moment, I've added all the functionality we need. We can update member information of who is selected, and delete them too. I think at this point the project is done.
