### ISSUE TITLE
Adding properties

### ISSUE THREAD

**Issue by lilyMonika** [lilyMonika/Team-Source-Control-Project#6]
Add properties for the Member class

**Comment by lilyMonika** [comment]
For the properties, I think the basics should be good.
Hence I think they should be:
-FirstName
-LastName
-DateOfBirth
-Favorite something

**Comment by Tfair5597** [comment]
Is the member class not made yet? I don't see it in there.

**Comment by lilyMonika** [comment]
There was one but I guess you made another one.

**Comment by Tfair5597** [comment]
Apologies, I didn't see the other one.
